AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2022-06-01
Description: Search Engine Revenue

Parameters:
  SourceBucketName: 
    Default: search-engine-revenue-input
    Type: String
  DestinationBucketName: 
    Default: search-engine-revenue-output
    Type: String

Resources:
  ## S3 bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName    
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName   

  ## Lambda function
  searchEngineRevenue:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/build/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      MemorySize: 2048      
      Role: 'arn:aws:iam::778722521407:role/MyLambdaRole'
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucketName
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucketName
      Environment:
        Variables:
          DESTINATION_BUCKETNAME: !Ref DestinationBucketName              
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
                
Outputs:
  SourceBucketName:
    Value: !Ref SourceBucketName
    Description: S3 Bucket for object storage
  DestinationBucketName:
    Value: !Ref DestinationBucketName
    Description: S3 destination Bucket for object storage
  FunctionArn:
    Value: !Ref searchEngineRevenue
    Description: searchEngineRevenue function  Arn